### ISSUE TITLE
Publication du module sur le store!

### ISSUE THREAD

**Issue by Pierre-Gilles** [atrovato/gladys-google-home#1]
Je viens de publier le module sur le store, beau boulot 👏

FR =>

https://developer.gladysassistant.com/fr/modules/google-home

EN =>

https://developer.gladysassistant.com/en/modules/google-home

**Comment by Pierre-Gilles** [comment]
Est-ce que tu pourrais mettre les mêmes exemples du README sur la page du module? :) 

Pour que les utilisateurs qui l'installe via Gladys voient comment s'en servir.

**Comment by atrovato** [comment]
AU fait, c'est fait :)
